nodeLinker: node-modules

packageExtensions:
  "@vue/babel-plugin-jsx@*":
    dependencies:
      "@babel/core": "*"
  "@vue/cli-service@*":
    dependencies:
      "@vue/cli-plugin-babel": "*"
      pug: "*"
      pug-plain-loader: "*"
      sass-loader: ^10
      vue-cli-plugin-pnp: "*"
      vue-template-compiler: ^2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
